<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-04T09:24:32Z" name="Default suite" finished-at="2021-07-04T09:24:59Z" duration-ms="27168">
    <groups>
    </groups>
    <test started-at="2021-07-04T09:24:32Z" name="Default test" finished-at="2021-07-04T09:24:59Z" duration-ms="27168">
      <class name="TestCaseClasses.BeingAtHomeTest">
        <test-method signature="testAtHomeCase()[pri:0, instance:TestCaseClasses.BeingAtHomeTest@4ff4357f]" started-at="2021-07-04T09:24:32Z" name="testAtHomeCase" finished-at="2021-07-04T09:24:54Z" duration-ms="22357" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Being-At-Home sub-menu is Missing in Collection Menu]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Being-At-Home sub-menu is Missing in Collection Menu
at org.testng.Assert.fail(Assert.java:96)
at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:68)
at pageClasses.HomePage.beingAtHome(HomePage.java:76)
at TestCaseClasses.BeingAtHomeTest.testAtHomeCase(BeingAtHomeTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAtHomeCase -->
        <test-method is-config="true" signature="flushReports()[pri:0, instance:TestCaseClasses.BeingAtHomeTest@4ff4357f]" started-at="2021-07-04T09:24:54Z" name="flushReports" finished-at="2021-07-04T09:24:59Z" duration-ms="4780" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
      </class> <!-- TestCaseClasses.BeingAtHomeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
